AmI = ""

.PHONY: build, clean, echo, copy


clean:
#ここを編集


build: main hello world all
main: main.c
#ここを編集

hello: hello.c
#ここを編集

world: world.c
#ここを編集

all: main.o hello.o world.o
#ここを編集



echo:
#ここを編集
	
